"""
tests/test_data_loader.py

Purpose:
    Unit tests for Module 1 (Data Acquisition): MATLAB loading, Touchstone
    loading, validation, and error handling for invalid/corrupted/missing
    files.

Input:
    Synthetic sample files in datasets/ (generated by
    datasets/generate_sample_data.py, created in setUpClass if missing).

Output:
    Standard unittest pass/fail results.
"""

from __future__ import annotations

import os
import sys
import unittest

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from data_loader.dataset_info import build_summary
from data_loader.loader import load_dataset
from data_loader.matlab_loader import load_matlab_dataset
from data_loader.physical_metadata import extract_physical_metadata_from_text
from data_loader.touchstone_loader import (
    load_touchstone_dataset,
    load_touchstone_s21_trace,
    parse_touchstone_header,
)
from data_loader.validator import (
    validate_dataset,
    validate_file_path,
    validate_frequencies,
    validate_s_parameters,
)
from utils.exceptions import (
    CorruptedFileError,
    EmptyDatasetError,
    InvalidFrequencyError,
    InvalidSParameterError,
    MissingVariableError,
    UnsupportedFileFormatError,
)

DATASETS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "datasets")


def _ensure_sample_data():
    required = [
        "sample_matlab.mat",
        "sample_matlab_v73.mat",
        "sample_touchstone.s2p",
        "corrupted.mat",
    ]
    if all(os.path.isfile(os.path.join(DATASETS_DIR, f)) for f in required):
        return
    sys.path.insert(0, DATASETS_DIR)
    import generate_sample_data as gen

    gen.generate_legacy_mat()
    gen.generate_v73_mat()
    gen.generate_touchstone()
    gen.generate_corrupted_file()


class TestFileValidation(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        _ensure_sample_data()

    def test_missing_file_raises(self):
        with self.assertRaises(FileNotFoundError):
            validate_file_path(os.path.join(DATASETS_DIR, "does_not_exist.mat"))

    def test_unsupported_extension_raises(self):
        bad_path = os.path.join(DATASETS_DIR, "not_supported.txt")
        with open(bad_path, "w") as f:
            f.write("hello")
        try:
            with self.assertRaises(UnsupportedFileFormatError):
                validate_file_path(bad_path)
        finally:
            os.remove(bad_path)

    def test_empty_file_raises(self):
        empty_path = os.path.join(DATASETS_DIR, "empty.s2p")
        open(empty_path, "wb").close()
        try:
            with self.assertRaises(EmptyDatasetError):
                validate_file_path(empty_path)
        finally:
            os.remove(empty_path)


class TestFrequencyValidation(unittest.TestCase):
    def test_valid_frequencies_pass(self):
        freqs = np.linspace(1e9, 9e9, 50)
        warnings = validate_frequencies(freqs)
        self.assertEqual(warnings, [])

    def test_empty_frequencies_raise(self):
        with self.assertRaises(EmptyDatasetError):
            validate_frequencies(np.array([]))

    def test_negative_frequencies_raise(self):
        freqs = np.array([-1e9, 1e9, 2e9])
        with self.assertRaises(InvalidFrequencyError):
            validate_frequencies(freqs)

    def test_nan_frequencies_raise(self):
        freqs = np.array([1e9, np.nan, 3e9])
        with self.assertRaises(InvalidFrequencyError):
            validate_frequencies(freqs)

    def test_unsorted_frequencies_warns(self):
        freqs = np.array([3e9, 1e9, 2e9])
        warnings = validate_frequencies(freqs)
        self.assertTrue(len(warnings) >= 1)


class TestSParameterValidation(unittest.TestCase):
    def test_valid_sparams_pass(self):
        s = (np.random.randn(50, 4) + 1j * np.random.randn(50, 4)) * 0.1
        warnings = validate_s_parameters(s, n_frequencies=50)
        self.assertIsInstance(warnings, list)

    def test_empty_sparams_raise(self):
        with self.assertRaises(EmptyDatasetError):
            validate_s_parameters(np.array([]), n_frequencies=0)

    def test_shape_mismatch_raises(self):
        s = np.random.randn(10, 4) + 1j * np.random.randn(10, 4)
        with self.assertRaises(InvalidSParameterError):
            validate_s_parameters(s, n_frequencies=50)

    def test_all_zero_sparams_raise(self):
        s = np.zeros((10, 4), dtype=complex)
        with self.assertRaises(InvalidSParameterError):
            validate_s_parameters(s, n_frequencies=10)

    def test_nan_sparams_raise(self):
        s = np.zeros((10, 4), dtype=complex)
        s[0, 0] = np.nan
        with self.assertRaises(InvalidSParameterError):
            validate_s_parameters(s, n_frequencies=10)


class TestMatlabLoader(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        _ensure_sample_data()

    def test_load_legacy_mat(self):
        dataset = load_matlab_dataset(os.path.join(DATASETS_DIR, "sample_matlab.mat"))
        self.assertEqual(dataset.file_type.startswith("MATLAB"), True)
        self.assertGreater(dataset.n_frequencies, 0)
        self.assertGreater(dataset.n_samples, 0)
        self.assertTrue(np.iscomplexobj(dataset.s_parameters))

    def test_load_v73_mat(self):
        dataset = load_matlab_dataset(os.path.join(DATASETS_DIR, "sample_matlab_v73.mat"))
        self.assertGreater(dataset.n_frequencies, 0)
        self.assertGreater(dataset.n_samples, 0)

    def test_corrupted_mat_raises(self):
        with self.assertRaises(CorruptedFileError):
            load_matlab_dataset(os.path.join(DATASETS_DIR, "corrupted.mat"))

    def test_summary_fields(self):
        dataset = load_matlab_dataset(os.path.join(DATASETS_DIR, "sample_matlab.mat"))
        summary = build_summary(dataset)
        display = summary.to_display_dict()
        for key in (
            "File Name",
            "File Type",
            "Number of Samples",
            "Number of Frequencies",
            "Frequency Range",
            "Number of Ports",
            "Dataset Size",
            "Available Variables",
        ):
            self.assertIn(key, display)

    def test_metadata_only_struct_file_gives_clear_error(self):
        """Regression test: a .mat file containing only MATLAB struct/cell
        arrays (e.g. a metadata-only file like 'train_md.mat') must raise
        a clear MissingVariableError, not crash with a numpy ValueError/
        TypeError while trying to astype(float) a struct array."""
        from scipy.io import savemat

        path = os.path.join(DATASETS_DIR, "_test_metadata_only.mat")
        savemat(path, {"scan_info": np.array([{"id": 1}, {"id": 2}], dtype=object)})
        try:
            with self.assertRaises(MissingVariableError) as ctx:
                load_matlab_dataset(path)
            self.assertIn("metadata-only", str(ctx.exception))
        finally:
            os.remove(path)

    def test_v73_complex_compound_dtype_is_converted(self):
        """Regression test: h5py represents MATLAB v7.3 complex arrays as
        a compound dtype with 'real'/'imag' fields; the loader must
        convert this to a native complex array instead of skipping it."""
        import h5py

        path = os.path.join(DATASETS_DIR, "_test_complex_struct.mat")
        with h5py.File(path, "w") as f:
            freqs = np.linspace(1e9, 8e9, 50)
            f.create_dataset("freq", data=freqs / 1e9)
            complex_data = np.random.randn(50, 4) + 1j * np.random.randn(50, 4)
            compound = np.zeros(complex_data.shape, dtype=[("real", "<f8"), ("imag", "<f8")])
            compound["real"] = complex_data.real
            compound["imag"] = complex_data.imag
            f.create_dataset("Es", data=compound)
        try:
            dataset = load_matlab_dataset(path)
            self.assertTrue(np.iscomplexobj(dataset.s_parameters))
            self.assertEqual(dataset.s_parameters.shape, (50, 4))
        finally:
            os.remove(path)

    def test_known_dataset_fallback_um_bmid(self):
        """UM-BMID fd_data cubes omit a frequency vector and store many scans.
        Loading requires an explicit scan_index and synthesizes 1-8 GHz / 1001 pts."""
        from scipy.io import savemat

        path = os.path.join(DATASETS_DIR, "_test_umbmid.mat")
        data = np.random.randn(5, 1001, 4) + 1j * np.random.randn(5, 1001, 4)
        savemat(path, {"fd_data_s11": data})
        try:
            with self.assertRaises(Exception):
                load_matlab_dataset(path)  # scan selection required
            dataset = load_matlab_dataset(path, scan_index=0)
            self.assertEqual(dataset.n_frequencies, 1001)
            np.testing.assert_allclose(dataset.freq_range_hz, (1e9, 8e9))
            self.assertEqual(dataset.s_parameters.shape, (1001, 4))
            self.assertAlmostEqual(dataset.metadata["antenna_radius_m"], 0.18, places=6)
        finally:
            os.remove(path)


class TestTouchstoneLoader(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        _ensure_sample_data()

    def test_load_s2p(self):
        dataset = load_touchstone_dataset(os.path.join(DATASETS_DIR, "sample_touchstone.s2p"))
        self.assertEqual(dataset.n_ports, 2)
        self.assertEqual(dataset.s_parameters.shape[1:], (2, 2))
        self.assertGreater(dataset.n_frequencies, 0)

    def test_unified_loader_dispatches_touchstone(self):
        dataset = load_dataset(os.path.join(DATASETS_DIR, "sample_touchstone.s2p"))
        self.assertIn("Touchstone", dataset.file_type)

    def test_parse_touchstone_header(self):
        header = parse_touchstone_header(os.path.join(DATASETS_DIR, "sample_touchstone.s2p"))
        self.assertEqual(header.frequency_unit, "GHZ")
        self.assertEqual(header.data_format, "RI")
        self.assertAlmostEqual(header.reference_impedance_ohm, 50.0)
        self.assertEqual(header.n_frequency_samples, 201)
        self.assertAlmostEqual(header.start_frequency_hz, 1e9)
        self.assertAlmostEqual(header.end_frequency_hz, 9e9)

    def test_load_touchstone_s21_trace_db_angle(self):
        path = os.path.join(DATASETS_DIR, "_test_db_angle.s2p")
        with open(path, "w", encoding="utf-8") as handle:
            handle.write("# MHz S DB R 75\n")
            handle.write("1000 0 0 -6 90 -6 -90 0 0\n")
            handle.write("2000 0 0 -20 180 -20 -180 0 0\n")
        try:
            frequencies_hz, s21, header = load_touchstone_s21_trace(path)
            np.testing.assert_allclose(frequencies_hz, np.array([1e9, 2e9]))
            self.assertEqual(header.data_format, "DB")
            np.testing.assert_allclose(s21[0], 10 ** (-6 / 20) * 1j, atol=1e-9)
            np.testing.assert_allclose(s21[1], -0.1 + 0j, atol=1e-9)
        finally:
            os.remove(path)

    def test_unified_loader_dispatches_matlab(self):
        dataset = load_dataset(os.path.join(DATASETS_DIR, "sample_matlab.mat"))
        self.assertIn("MATLAB", dataset.file_type)

    def test_unsupported_extension_via_unified_loader(self):
        bad_path = os.path.join(DATASETS_DIR, "unsupported.xyz")
        with open(bad_path, "w") as f:
            f.write("data")
        try:
            with self.assertRaises(UnsupportedFileFormatError):
                load_dataset(bad_path)
        finally:
            os.remove(bad_path)


class TestPhysicalMetadataParsing(unittest.TestCase):
    def test_extract_physical_metadata_from_text(self):
        text = (
            "antenna radius=8 cm; wave speed=2.1e8 m/s; "
            "x span=-6 cm to 6 cm; y span=-4 cm to 4 cm"
        )
        metadata = extract_physical_metadata_from_text(text)
        self.assertAlmostEqual(metadata["antenna_radius_m"], 0.08)
        self.assertAlmostEqual(metadata["wave_speed_m_per_s"], 2.1e8)
        self.assertEqual(metadata["reconstruction_x_span_m"], (-0.06, 0.06))
        self.assertEqual(metadata["reconstruction_y_span_m"], (-0.04, 0.04))


if __name__ == "__main__":
    unittest.main()
